hyperledger-labs/fabric-builder-k8s

- README.md
- cmd/run/main.go
- docs/TEST_NETWORK_K8S.md
- internal/util/k8s.go
Should default to using the test-network namespace in the k8s test network
The namespace can be set explicitly using the KUBE_NAMESPACE environment variable and will default to “default” if neither is set
Also clean up usage docs
> Read namespace from service account

- internal/builder/run.go
The peer only wants to start the chaincode once but gets two connections due to “Replicas” being set to 2, which causes an error in the peer log
> Update run to correct number of replicas

- .github/workflows/go.yml
Dynamically linked binaries were causing issues in alpine containers
> Build static binaries

- README.md
- internal/util/env.go
Follow the convention of the CCaaS builder which uses a `CHAINCODE_AS_A_SERVICE_BUILDER_` prefix to make it more obvious what the environment variable relates to
> Rename FABRIC_CHAINCODE_NAMESPACE variable

- docs/TEST_NETWORK_K8S.md
- internal/builder/run.go
- internal/util/k8s.go
If the chaincode pod already exists when the peer calls run, delete and recreate the pod so that the chaincode calls the peer again
> Restart any existing chaincode pod

- README.md
- internal/log/log.go
The peer logging already includes UTC timestamp and the builder name, e.g.
```
2022-06-14 08:44:40.442 UTC 0243 INFO [chaincode.externalbuilder.k8s_builder] waitForExit -> 2022/06/14 08:44:40.442618 log.go:122: fabric-builder-k8s : /var/hyperledger/fabric/external_builders/k8s_builder/bin/release [35]: Release output directory: /tmp/fabric-conga-nft-contract-56c554c330cf883d7f0cf21521aba5abce1159513e708bcf3fcfbb2e27ef92ad2871683330/release command=release
```
> Simplify logger prefix

- internal/builder/run.go
The previous commit broke the run binary by trying to read chaincode.json in the build output directory, instead of the run metadata directory
```
2022-06-20 09:05:10.059 UTC 063c INFO [chaincode.externalbuilder.k8s_builder] waitForExit -> /var/hyperledger/fabric/external_builders/k8s_builder/bin/run [53]: Error running chaincode: unable to read /var/hyperledger/fabric/data/org1-peer1.org1.example.com/externalbuilder/builds/conga-nft-contract-5361d5fdb30a8046e37d7db106471f2fed13bacafe85b93b9b39e8bdf00546b0/bld/chaincode.json: open /var/hyperledger/fabric/data/org1-peer1.org1.example.com/externalbuilder/builds/conga-nft-contract-5361d5fdb30a8046e37d7db106471f2fed13bacafe85b93b9b39e8bdf00546b0/bld/chaincode.json: no such file or directory command=run
```
Signed-off-by: James Taylor …
> Read chaincode.json from the correct directory

- .github/workflows/docker-build.yml
- .github/workflows/go-contract-image.yml
- .github/workflows/java-contract-image.yml
- .github/workflows/node-contract-image.yml
Sample contracts should be packaged for the k8s builder, but not the k8s builder image itself
> Fix sample contract packaging

- cmd/detect/main.go
- cmd/detect/main_test.go
- cmd/run/main_test.go
- cmd/run/run_suite_test.go
- internal/builder/detect.go
- internal/builder/run.go
- always log the chaincode pod details in the run phase
- avoid spamming peer log for unsupported chaincode in the detect phase
> Improve logging

- .github/workflows/go.yml
For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Update workflows with latest versions of GitHub actions

- .github/workflows/docker-build.yml
- .github/workflows/go.yml
Use GitHub cli to upload assets to release instead of the softprops/action-gh-release action
> Fix GHA node deprecation warning

- .github/workflows/docker-build.yml
Add checkout step- the gh cli needs to be run in a git repository
> Fix chaincode package uploads

- cmd/run/main_test.go
- internal/util/k8s.go
- internal/util/k8s_test.go
- internal/util/util_suite_test.go
Generate a valid RFC 1035 label name from an MSP ID, peer ID, and chaincode ID.
Closes #16
> Fix k8s object names

- .github/workflows/docker-build.yml
It should be possible to build arm peer images once Fabric 2.5 is LTS but stop building arm docker images for now
Closes #74
> Stop building arm docker images

- Dockerfile
From 2.5.0, Fabric switches base docker images from golang-alpine to ubuntu 20.
This patch follows this update.
Resolves #91
> Update amd64 Dockerfile from alpine-based to ubuntu-based

- .github/workflows/docker-build.yml
The peer images are based on Fabric 2.5 now, which should support arm
> Re-enable building arm docker images

- cmd/release/main_test.go
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/collections/assetCollection/indexes/indexOwner.json
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/collections/fabCarCollection/indexes/indexOwner.json
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/collections/fabCarCollection/subdir/indexes/indexOwner.json
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/collectionsd/assetCollection/indexes/indexOwner.json
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/collectionsd/fabCarCollection/indexes/indexOwner.json
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/collectionsd/fabCarCollection/subdir/indexes/indexOwner.json
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/indexOwner.json
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/indexed/indexOwner.json
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/indexed/subdir/indexOwner.json
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/indexed/test.txt
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/subdir/indexes/indexOwner.json
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/subdir/indexes/subdir/indexOwner.json
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/subdir/indexes/test.txt
- cmd/release/testdata/buildwithindexes/META-INF/statedb/couchdb/test.txt
- internal/builder/release.go
- internal/util/copy.go
Related to issue: #106 
Problem when private data indexing is needed.
> Copy statedb/couchdb recursively discarding non .json files to create index for public and private data assets.

- .devcontainer/devcontainer.json
- .devcontainer/postCreateCommand.sh
- .gitignore
- CONTRIBUTING.md
- docs/KUBERNETES_CONFIG.md
Simplify local development with instructions to use the Fabric nano
test network with minikube
> Add minikube to devcontainer

- cmd/run/main.go
- cmd/run/main_test.go
- cmd/run/testdata/validchaincode/chaincode.json
- internal/builder/run.go
- internal/util/env.go
- internal/util/fabric.go
- internal/util/fabric_test.go
- internal/util/k8s.go
- internal/util/k8s_test.go
> Improve kubernetes object names

- CONTRIBUTING.md
- cmd/run/main_test.go
- internal/builder/run.go
- internal/util/k8s.go
- internal/util/k8s_test.go
> Run chaincode using jobs

- docs/getting-started/demo.md
Update to the 0.14.0 release and matching test-network-k8s commit
> Update quick start guide

- docs/tutorials/develop-chaincode.md
- mkdocs.yml
- samples/node-contract/package.json
> Add developing chaincode tutorial

- .github/workflows/docker-build.yml
Pushing to ghcr has started failing with 403 Forbidden Hopefully this will fix it although there may also be some org permissions to update
> Update docker build permissions

- .github/workflows/docker-build.yml
- .github/workflows/go-contract-image.yml
- .github/workflows/go.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/java-contract-image.yml
- .github/workflows/mkdocs.yml
- .github/workflows/node-contract-image.yml
- .github/workflows/peer-image.yml
- .github/workflows/status-checks-docker.yml
- .github/workflows/status-checks.yml
- Dockerfile
Permissions should be read only by default
Related to #174
> Fix top level permissions in workflows

- .github/workflows/docker-build.yml
The sample contract images were all building with the peer context instead of the correct sample contexts
> Fix sample contract image builds

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
The xxd command can be used to encode chaincode package hashes, as used by the k8s builder to label chaincode jobs and pods
For example:
```
peer lifecycle chaincode calculatepackageid go-contract.tgz | cut -d':' -f2 | xxd -r -p | base32 | tr -d '='
```
> Add xxd to dev container

- docs/concepts/chaincode-job.md
- docs/configuring/overview.md
- docs/getting-started/demo.md
- docs/getting-started/install.md
- docs/tutorials/bevel-operator.md
- docs/tutorials/package-chaincode.md
- mkdocs.yml
Also documents removing vm.endpoint from core.yaml and other minor
updates
See https://github.com/hyperledger-labs/fabric-builder-k8s/issues/229 and https://github.com/hyperledger-labs/fabric-builder-k8s/issues/223
> Add chaincode job concept to doc
