hyperledger-labs/fabric-builder-k8s

Dockerfile, README.md, internal/builder/run.go
Also fix core.yaml and add namespace to pod list
=> Update readme with chaincode install instructions

cmd/run/main.go, cmd/run/testdata/validchaincode/chaincode.json, cmd/run/testdata/validimage/image.json, go.mod, internal/builder/release.go, internal/builder/run.go
Not a real chaincode deployment yet!
=> Update run to create a deployment

README.md, internal/builder/run.go
The system:serviceaccount:test-network:default service account needs to be able to create a deployment
=> Add basic k8s role binding info to readme

go.mod
=> Update go.mod version to 1.17

internal/builder/run.go
=> Add secrets for certs

README.md, cmd/run/main.go, internal/builder/run.go, internal/util/k8s.go
There are lots of hacks but it just about works!
=> Complete initial proof of concept

Dockerfile, README.md, cmd/run/main.go, docs/TEST_NETWORK_K8S.md, internal/util/env.go
=> Rename namespace variable

.github/workflows/go.yml
=> Add Go build and release workflow

README.md, docs/TEST_NETWORK_K8S.md, docs/TEST_NETWORK_NANO.md, internal/builder/run.go, internal/util/files.go, internal/util/k8s.go
Image tags can change so it’s safer to use the digest instead
=> Use image digest

.gitignore, internal/util/k8s.go
Signed-off-by: Josh Kneubuhl <jkneubuh@us.ibm.com>
=> Remove 0x400 permission restriction for non UID 0 CC containers

.github/workflows/docker-image.yml, Dockerfile
Use OCI annotations to label the peer image
=> Add OCI labels

README.md
=> Clarify Fabric builder constraints in readme

README.md, docs/FABRIC_OPERATOR.md, docs/TEST_NETWORK_K8S.md
=> Add fabric operator docs

README.md, docs/HLF_OPERATOR.md
=> Add hlf-operator docs

.github/workflows/docker-image.yml, Dockerfile, cmd/build/build_suite_test.go, cmd/build/main.go, cmd/detect/detect_suite_test.go, cmd/detect/main.go, cmd/release/main.go, cmd/release/release_suite_test.go, cmd/run/main.go, docs/FABRIC_OPERATOR.md, docs/HLF_OPERATOR.md, docs/TEST_NETWORK_NANO.md, go.mod, internal/builder/build.go, internal/builder/detect.go, internal/builder/release.go, internal/builder/run.go, internal/util/copy.go, internal/util/files.go, internal/util/k8s.go
Update things for the new hyperledger-labs organisation
=> Move from hyperledgendary to hyperledger-labs

README.md, docs/FABRIC_OPERATOR.md, docs/HLF_OPERATOR.md, docs/TEST_NETWORK_K8S.md, docs/TEST_NETWORK_NANO.md
=> Update docs for newly published sample contracts

README.md
Update the "above the fold" README for k8s-builder.
Signed-off-by: Josh Kneubuhl <jkneubuh@us.ibm.com>
=> Top README refresh, circa v0.7.2

.github/workflows/go.yml
=> Build arm binaries

.github/workflows/docker-build.yml, .github/workflows/go-contract-image.yml, .github/workflows/java-contract-image.yml, .github/workflows/node-contract-image.yml, .github/workflows/peer-image.yml
Also fixes bug with "/" characters in image names, although chaincode labels now have the same issue since they are used in filenames!
=> Build multi-platform docker images

.github/workflows/docker-build.yml, .github/workflows/go.yml
Fix no such file errors for binaries and chaincode packages
=> Fix release asset uploads

.github/workflows/status-checks.yml
See:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
=> Handle skipped but required status checks

README.md, docs/KUBERNETES_CONFIG.md
Includes details of how to provide image pull secrets when chaincode images are in registries which require credentials
Closes #65
=> Update docs with general Kubernetes config info

README.md
=> Remove unnecessary bullets in readme

.github/workflows/docker-build.yml, .github/workflows/go.yml, .github/workflows/golangci-lint.yml
Fixes Node.js 16 deprecation warnings
=> Update github checkout and setup-go actions

cmd/release/main_test.go, cmd/release/testdata/buildwithindexes/image.json, cmd/release/testdata/buildwithoutindexes/image.json, internal/util/copy.go
=> Fix release for packages without indexes

docs/configuring/kubernetes-permissions.md
The latest implementation uses jobs
Still need to work out the exact permissions required- see #52
=> Update kubernetes permissions

docs/about/community.md
=> Update community page

Dockerfile, samples/go-contract/Dockerfile, samples/java-contract/Dockerfile, samples/node-contract/Dockerfile
=> Fix Docker build warnings

CODE_OF_CONDUCT.md
Now with the new LF Decentralized Trust code of conduct
See #209
=> Update code of conduct again

.github/workflows/docker-build.yml, .github/workflows/go.yml, .github/workflows/golangci-lint.yml, .github/workflows/mkdocs.yml, .github/workflows/ossf-scorecard.yml
=> Pin GitHub workflow dependencies by hash

.github/workflows/docker-build.yml, .github/workflows/go-contract-image.yml, .github/workflows/java-contract-image.yml, .github/workflows/node-contract-image.yml, .github/workflows/peer-image.yml
Another attempt to get the permissions right!
=> Fix top level permissions in workflows again

docs/getting-started/demo.md
=> Update quick start guide

.devcontainer/Dockerfile
=> Update dev container
